{% set name = "ImagingReso" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0154b826ce987d8d54124369ad3905587e6cdce1bc04f31ed8a76598512407a1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - matplotlib
    - periodictable
    - numpy
    - scipy
    - pandas
    - six
    - plotly

test:
  imports:
    - ImagingReso

about:
  home: https://github.com/ornlneutronimaging/ImagingReso
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: a tool to simulate neutron resonance signal for neutron resonance imaging
  doc_url: http://imagingreso.readthedocs.io/
  dev_url: https://github.com/ornlneutronimaging/ImagingReso

extra:
  recipe-maintainers:
    - zhangy6x
    - JeanBilheux
