{% set name = "ImagingReso" %}
{% set version = "1.6.15" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "537ee9ec05796a0fa3e6023c88f4678dd92fbf9559a20ea0e9ee11d90259df6c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  
requirements:
  build:
    - python
    - pip
  run:
    - python
    - matplotlib
    - periodictable
    - numpy
    - scipy
    - pandas
    - six
    - plotly
    
test:
  imports:
    - ImagingReso

about:
  home: https://github.com/ornlneutronimaging/ImagingReso
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'a tool to simulate neutron resonance signal for neutron resonance imaging'
  doc_url: http://imagingreso.readthedocs.io/
  dev_url: https://github.com/ornlneutronimaging/ImagingReso

extra:
  recipe-maintainers:
    - zhangy6x
    - JeanBilheux
