travis:
  secure:
    BINSTAR_TOKEN: VM6MV/BCbyt8iPcoZoazDK7KUY15q7QanETcVWur/ID2lgc+clruakjXtjnCPrSIVROF+36fHO5T5UDSjAbWSAG3tBl5nzCVhvddLOw0oFJtEduNGaidYBVNhRaJ7ie0CSUcQbC4/vjt44/U9D9D0T0x2clHVbtLu7f2d7kY9Fe0QXpjYGAD2r6C3dfoAwzzAgS14MQ87g6hjf4Txgj1KT8hgEbJvsnUwMS+duSc7Qwvf44+ihifJ9glJrkevt3qkdIMdqadjbEDkfFQZZ96Lty1QLvjY5SLH3RzGdHMi6odl2Ze0WaHLVurBU8YFaueHxnH5lHX/+BGx0YXHPeup7cGKqqiHfkYpvO5Bsk1GEjT/ESJE+wLpQ8AIK/+uRFPSiOq8EmneNyANVKHuIm6C+2vUgdE7QBwJmaWAa7+XvGV/fqKwTLHIxIkbUZFbSPiefsz18GoZ1mH6/TccXu6fVGjyEexbBqDiYXL67DwkZI4+zPksg4FEFbct0ttr5Jz5QW8i7nM3PNmo18bHEpt+Tt+K4nlIPcu/uRy6UCG1w2+JqZ6ENgdhTJerfKqKWDlvglHQXCwiv/epbwmawKLJqralHfyqxjDuymBX/mRZSEwtOzMWYFpw49ZaerLpaWn/gATFpRqd9/xuQBcVcOgkJ9Pw14J7fA4lR8Wi0SUOjs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
