travis:
  secure:
    BINSTAR_TOKEN: h5TVJgubxtFRMG8t3iiHm+FQORy+NLkPhe/1RapjwSXfAkyIn+yltyBOeAVGUyIeRB8Oed2jtOieEnU12DwtDSZo+rHBslZAVNLXZw0Nxq/C4jj5skRu0OyBvd64z2fuZavhIRZyDlVgROvjPxk1FHSTr5csx5PtUEx6AnUiDPnDdrKvhWemslskelMM6bw+DwWmhjBJ6mZjX6faqy2QpzeDZo6jrWDbZP4JzXpm8IV8IOXMBlGYoH4diergayznrRcUGKmpYuxKCYVdkWErNXVJK6vYtpSgHl7DRKJqqfW7o/Pa+TFLT4yVS+LtII/XQIDF6f/FjUwFGuA6qCLBkgxp/UbNv7hlHN1Z7wQUDzUKetn5CPfzCanP4Kwcsjzsh0/TAXJhA+4lTHh/TqxXCyyoqOH7HqaQzOkBfa2/Wl4ZxF+Ov8CPiTARWg8GGeOTc74D+a4GksGBqCCt3GEuvk8TEFyhn6biKJBniLYQFC10GQGXCSdAS2BpYTmpUz2A9WqJBP/3Bx4Un0g48teukCR45NTiLCU5LWqWI3+SvXhBoDqK3GhIxvgJJXKIrBP2oz8XDZhsxxc6yQdMeL22o0CX3U4NDCJBVV1AHxcF0eiAkdivH7ngGKkWt4CupsG2867l2Nd8WLoCqedxnYOptSTDAAzprDFC2h0+a9OJsVQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
